import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/context/UserContext";
import localFont from "next/font/local";
import { MessageContextProvider } from "@/context/MessageContext";

const satoshi = localFont({
	src: [
		{
			path: "../public/fonts/Satoshi-Variable.ttf",
		},
	],
	variable: "--font-satoshi",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable}`}
			>
				<UserContextProvider>
					<MessageContextProvider>{children}</MessageContextProvider>
				</UserContextProvider>
			</body>
		</html>
	);
}
